sudo: require
language: generic 
services:
  - docker

before_install:
  - docker build -t pdeshpan/docker-react-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true pdeshpan/docker-react-dev npm run test 
